In [1]:
# ============================================================
# WORLD BANK DATASET INSPECTION
# ============================================================

import pandas as pd
import os

print("=" * 60)
print("WORLD BANK DATASET INSPECTION")
print("=" * 60)

# Project root
project_root = os.path.abspath("..")

# Dataset paths
kaggle_data_path = os.path.join(
    project_root,
    "raw",
    "kaggle",
    "World Bank Data.csv"
)

kaggle_metadata_path = os.path.join(
    project_root,
    "raw",
    "kaggle",
    "World Bank Metadata.csv"
)

world_bank_excel_path = os.path.join(
    project_root,
    "raw",
    "world_bank",
    "DataDetails.xlsx"
)

print("\nKaggle World Bank Data:")
print(kaggle_data_path)

print("\nKaggle World Bank Metadata:")
print(kaggle_metadata_path)

print("\nWorld Bank Excel:")
print(world_bank_excel_path)

print("\nFiles available:")

for path in [
    kaggle_data_path,
    kaggle_metadata_path,
    world_bank_excel_path
]:
    print(
        "✓" if os.path.exists(path) else "❌",
        os.path.basename(path)
    )

============================================================
WORLD BANK DATASET INSPECTION
============================================================

Kaggle World Bank Data:
c:\Users\Intel\OneDrive\Desktop\data_eda\raw\kaggle\World Bank Data.csv

Kaggle World Bank Metadata:
c:\Users\Intel\OneDrive\Desktop\data_eda\raw\kaggle\World Bank Metadata.csv

World Bank Excel:
c:\Users\Intel\OneDrive\Desktop\data_eda\raw\world_bank\DataDetails.xlsx

Files available:
❌ World Bank Data.csv
❌ World Bank Metadata.csv
✓ DataDetails.xlsx

In [2]:
# ============================================================
# INSPECT WORLD BANK EXCEL WORKBOOK
# ============================================================

import pandas as pd
import os

excel_path = os.path.join(
    project_root,
    "raw",
    "world_bank",
    "DataDetails.xlsx"
)

print("=" * 60)
print("WORLD BANK EXCEL WORKBOOK INSPECTION")
print("=" * 60)

# Load workbook information
excel_file = pd.ExcelFile(excel_path)

print("\n========== SHEETS ==========")

print("Number of sheets:", len(excel_file.sheet_names))

for i, sheet in enumerate(excel_file.sheet_names, start=1):
    print(f"{i}. {sheet}")

print("\n========== WORKBOOK INSPECTION COMPLETE ==========")

============================================================
WORLD BANK EXCEL WORKBOOK INSPECTION
============================================================

========== SHEETS ==========
Number of sheets: 4
1. MAIN
2. www.enterprisesurveys.org
3. Details for Sector and Location
4. Details for Informal Sector ES

========== WORKBOOK INSPECTION COMPLETE ==========

In [3]:
# ============================================================
# INSPECT WORLD BANK MAIN SHEET
# ============================================================

import pandas as pd

main_df = pd.read_excel(
    excel_path,
    sheet_name="MAIN"
)

print("=" * 60)
print("WORLD BANK MAIN SHEET INSPECTION")
print("=" * 60)

print("\nDataset shape:")
print(main_df.shape)

print("\nNumber of rows:", len(main_df))
print("Number of columns:", len(main_df.columns))

print("\n========== COLUMN NAMES ==========")

for i, column in enumerate(main_df.columns, start=1):
    print(f"{i}. {column}")

print("\n========== FIRST 5 ROWS ==========")

display(main_df.head())

print("\n========== DATA TYPES ==========")

print(main_df.dtypes)

print("\n========== INSPECTION COMPLETE ==========")

============================================================
WORLD BANK MAIN SHEET INSPECTION
============================================================

Dataset shape:
(28, 2)

Number of rows: 28
Number of columns: 2

========== COLUMN NAMES ==========
1. Unnamed: 0
2. Unnamed: 1

========== FIRST 5 ROWS ==========

   Unnamed: 0                        Unnamed: 1
0         NaN                Enterprise Surveys
1         NaN  http://www.enterprisesurveys.org
2         NaN                               NaN
3         NaN                  Questions? Email
4         NaN   enterprisesurveys@worldbank.org

========== DATA TYPES ==========
Unnamed: 0    float64
Unnamed: 1        str
dtype: object

========== INSPECTION COMPLETE ==========

In [4]:
# ============================================================
# WORLD BANK DATASET — MAIN SHEET INSPECTION
# ============================================================

import pandas as pd

world_bank_file = "../raw/world_bank/DataDetails.xlsx"

# Load the MAIN sheet
world_bank_main = pd.read_excel(
    world_bank_file,
    sheet_name="MAIN"
)

print("=" * 60)
print("WORLD BANK MAIN SHEET INSPECTION")
print("=" * 60)

print("\nDataset shape:")
print(world_bank_main.shape)

print("\nNumber of rows:", world_bank_main.shape[0])
print("Number of columns:", world_bank_main.shape[1])

print("\n========== COLUMN NAMES ==========")

for i, col in enumerate(world_bank_main.columns, 1):
    print(f"{i}. {col}")

print("\n========== FIRST 5 ROWS ==========")
display(world_bank_main.head())

print("\n========== DATA TYPES ==========")
print(world_bank_main.dtypes)

print("\n========== LAST 5 ROWS ==========")
display(world_bank_main.tail())

print("\n========== MAIN SHEET INSPECTION COMPLETE ==========")

============================================================
WORLD BANK MAIN SHEET INSPECTION
============================================================

Dataset shape:
(28, 2)

Number of rows: 28
Number of columns: 2

========== COLUMN NAMES ==========
1. Unnamed: 0
2. Unnamed: 1

========== FIRST 5 ROWS ==========

   Unnamed: 0                        Unnamed: 1
0         NaN                Enterprise Surveys
1         NaN  http://www.enterprisesurveys.org
2         NaN                               NaN
3         NaN                  Questions? Email
4         NaN   enterprisesurveys@worldbank.org

========== DATA TYPES ==========
Unnamed: 0    float64
Unnamed: 1        str
dtype: object

========== LAST 5 ROWS ==========

    Unnamed: 0                                         Unnamed: 1
23         NaN  The International Standard Industrial Classifi...
24         NaN   is to provide a set of activity categories th...
25         NaN                                                NaN
26         NaN  More details of ISIC Rev 4.0 can be found in t...
27         NaN  https://unstats.un.org/unsd/classifications/Fa...

========== MAIN SHEET INSPECTION COMPLETE ==========

In [5]:
# ============================================================
# WORLD BANK EXCEL — INSPECT ALL REMAINING SHEETS
# ============================================================

import pandas as pd

excel_path = "../raw/world_bank/DataDetails.xlsx"

# Load workbook
xls = pd.ExcelFile(excel_path)

print("=" * 70)
print("WORLD BANK EXCEL SHEET INSPECTION")
print("=" * 70)

for sheet in xls.sheet_names:
    print(f"\n{'=' * 20} {sheet} {'=' * 20}")
    
    df_temp = pd.read_excel(
        excel_path,
        sheet_name=sheet
    )
    
    print("Shape:", df_temp.shape)
    print("Rows:", len(df_temp))
    print("Columns:", len(df_temp.columns))
    
    print("\nColumn names:")
    for i, col in enumerate(df_temp.columns, 1):
        print(f"{i}. {col}")
    
    print("\nFirst 5 rows:")
    display(df_temp.head())

print("\n" + "=" * 70)
print("SHEET INSPECTION COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK EXCEL SHEET INSPECTION
======================================================================

==================== MAIN ====================
Shape: (28, 2)
Rows: 28
Columns: 2

Column names:
1. Unnamed: 0
2. Unnamed: 1

First 5 rows:

   Unnamed: 0                        Unnamed: 1
0         NaN                Enterprise Surveys
1         NaN  http://www.enterprisesurveys.org
2         NaN                               NaN
3         NaN                  Questions? Email
4         NaN   enterprisesurveys@worldbank.org

==================== www.enterprisesurveys.org ====================
Shape: (564, 28)
Rows: 564
Columns: 28

Column names:
1. Data Details
2. Unnamed: 1
3. Unnamed: 2
4. Unnamed: 3
5. Unnamed: 4
6. Unnamed: 5
7. Unnamed: 6
8. Unnamed: 7
9. Number of Firms
10. Unnamed: 9
11. Unnamed: 10
12. Unnamed: 11
13. Unnamed: 12
14. Unnamed: 13
15. Unnamed: 14
16. Unnamed: 15
17. Unnamed: 16
18. Unnamed: 17
19. Unnamed: 18
20. Unnamed: 19
21. Unnamed: 20
22. Unnamed: 21
23. Unnamed: 22
24. Notes
25. Unnamed: 24
26. Unnamed: 25
27. Unnamed: 26
28. Unnamed: 27

First 5 rows:

,Data Details,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Number of Firms,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Notes,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,By Stratification Variables*,...,Ownership,NaN,Trade Orientation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country,Year,Fiscal Year,n3_l2_year,Number of sub-national regions,Duration of Fieldwork,Methodology,Region,Total,Small (5-19 employees),...,Domestically-owned,Foreign-owned,Exporters,Non-exporters,Firms without female participation in ownership,Country Specific Topics,Other Surveys Available,Panel Data,Panel Data Details,Other Notes
2,Afghanistan,2008,2007/2008,2005/2006,6,10/2008 - 12/2008,Global,MENAAP,535,347,...,507,23,12,519,519,"Entrepreneurship, ICT, Trade, Access to Land, ...",Informal,2005-2008,both waves (58),NaN
3,Afghanistan,2014,2012/2013,2010/2011,5,5/2013 - 7/2014,Global,MENAAP,410,256,...,410,0,13,358,399,"Infrastructure, Gender, Trade, Labor",Gender,2008-2010-2014,"all waves (38), last two waves (24), first two...",NaN
4,Afghanistan,2025,2024/2025,2022/2023,4,7/2025-01/2026,Global,MENAAP,426,221,...,421,5,32,394,345,Mining,Informal,2005-2008-2014-2025,NaN,NaN

==================== Details for Sector and Location ====================
Shape: (564, 61)
Rows: 564
Columns: 61

Column names:
1. Data Details
2. Unnamed: 1
3. Unnamed: 2
4. Unnamed: 3
5. Unnamed: 4
6. Unnamed: 5
7. Unnamed: 6
8. Unnamed: 7
9. Unnamed: 8
10. Levels of Location Strata
11. Levels of Business Sector Strata
12. ISIC Rev. 3.1 (http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=17)
13. Unnamed: 12
14. Unnamed: 13
15. Unnamed: 14
16. Unnamed: 15
17. Unnamed: 16
18. Unnamed: 17
19. Unnamed: 18
20. Unnamed: 19
21. Unnamed: 20
22. Unnamed: 21
23. Unnamed: 22
24. Unnamed: 23
25. Unnamed: 24
26. Unnamed: 25
27. Unnamed: 26
28. Unnamed: 27
29. Unnamed: 28
30. Unnamed: 29
31. Unnamed: 30
32. Unnamed: 31
33. Unnamed: 32
34. Unnamed: 33
35. Unnamed: 34
36. Unnamed: 35
37. Unnamed: 36
38. Unnamed: 37
39. Unnamed: 38
40. Unnamed: 39
41. Unnamed: 40
42. Unnamed: 41
43. Unnamed: 42
44. Unnamed: 43
45. Unnamed: 44
46. Unnamed: 45
47. Unnamed: 46
48. Unnamed: 47
49. Unnamed: 48
50. Unnamed: 49
51. Unnamed: 50
52. Unnamed: 51
53. Unnamed: 52
54. Unnamed: 53
55. Unnamed: 54
56. Unnamed: 55
57. Unnamed: 56
58. Unnamed: 57
59. Unnamed: 58
60. Unnamed: 59
61. Unnamed: 60

First 5 rows:

,Data Details,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Levels of Location Strata,...,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Professional, scientific and technical activities",NaN,NaN,NaN,NaN,NaN,NaN,Others,NaN,Additional
1,Country,Year,Fiscal Year,n3_l2_year,Number of sub-national regions,Duration of Fieldwork,Methodology,Region,Total,Number of firms in each subnational location l...,...,ISIC 4.0: 69,ISIC 4.0: 70,ISIC 4.0: 71,ISIC 4.0: 72,ISIC 4.0: 73,ISIC 4.0: 74,ISIC 4.0: 75,ISIC 4.0: 79,ISIC 4.0: 95,NaN
2,Afghanistan,2008,2007/2008,2005/2006,6,10/2008 - 12/2008,Global,MENAAP,535,"5 Smaller Cities (Bamyan,Ghazni,Khost,Kunduz,P...",...,0,0,0,0,0,0,0,0,0,2
3,Afghanistan,2014,2012/2013,2010/2011,5,5/2013 - 7/2014,Global,MENAAP,410,"Herat (69), Jalalabad (71), Kabul (128), Kanda...",...,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,2025,2024/2025,2022/2023,4,7/2025-01/2026,Global,MENAAP,426,"East & Southeast (56), Kabul (152), North (94)...",...,3,0,1,0,1,0,1,1,0,0

==================== Details for Informal Sector ES ====================
Shape: (40, 15)
Rows: 40
Columns: 15

Column names:
1. Country
2. Cities / Regions
3. Year
4. Duration of Fieldwork
5. Methodology
6. Region
7. Informal businesses enumerated
8. Long-form interviews completed
9. Making Goods
10. Retail
11. Other Services
12. Firms operating out of household
13. Firms without female participation in ownership
14. Country Specific Topics
15. Other Surveys Available

First 5 rows:

,Country,Cities / Regions,Year,Duration of Fieldwork,Methodology,Region,Informal businesses enumerated,Long-form interviews completed,Making Goods,Retail,Other Services,Firms operating out of household,Firms without female participation in ownership,Country Specific Topics,Other Surveys Available
0,Cabo Verde,"Mindelo, Praia",2006,2/2006 - 3/2006,RW,AFR,NaN,103,31.0,64.0,9.0,NaN,NaN,NaN,"ES, Tourism"
1,Cameroon,"Bafoussam, Douala, Yaounde",2006,1/2006 - 3/2006,RW,AFR,NaN,99,33.0,26.0,40.0,17.0,70.0,NaN,"ES, Tourism"
2,Afghanistan,"Bamyan, Kabul, Ghazni, Khost, Hirat, Kandahar,...",2008,10/2008 - 11/2008,Other,MENAAP,NaN,419,105.0,106.0,208.0,NaN,412.0,NaN,ES
3,"Egypt, Arab Rep.","Cairo, Alexandria, Damita, Giza, Fayoum, Assui...",2008,8/2008 - 9/2008,RW,MENAAP,NaN,500,134.0,298.0,68.0,71.0,421.0,NaN,"Hotels, ES"
4,Burkina Faso,"Bobo-Dioulasso, Ouagadougou",2009,6/2008 - 7/2008,RW,AFR,NaN,120,70.0,NaN,NaN,34.0,95.0,NaN,"Micro, ES"

======================================================================
SHEET INSPECTION COMPLETE
======================================================================

In [6]:
# ============================================================
# INSPECT KAGGLE RAW DATA FOLDER
# ============================================================

import os

kaggle_path = os.path.join(
    project_root,
    "raw",
    "kaggle"
)

print("=" * 60)
print("KAGGLE RAW DATA FOLDER")
print("=" * 60)

if os.path.exists(kaggle_path):

    files = os.listdir(kaggle_path)

    print("\nItems found:", len(files))

    if len(files) == 0:
        print("❌ Folder is empty.")

    else:
        for i, item in enumerate(files, 1):

            full_path = os.path.join(kaggle_path, item)

            if os.path.isfile(full_path):
                size_mb = os.path.getsize(full_path) / (1024 * 1024)
                print(f"{i}. FILE   {item}   ({size_mb:.2f} MB)")

            elif os.path.isdir(full_path):
                print(f"{i}. FOLDER {item}")

else:
    print("❌ Kaggle folder does not exist.")

print("\n" + "=" * 60)
print("FOLDER INSPECTION COMPLETE")
print("=" * 60)

============================================================
KAGGLE RAW DATA FOLDER
============================================================

Items found: 2
1. FILE   b23ed973-2503-460a-bdd9-8c998125c5f1_Data.csv   (2.03 MB)
2. FILE   b23ed973-2503-460a-bdd9-8c998125c5f1_Series - Metadata.csv   (0.04 MB)

============================================================
FOLDER INSPECTION COMPLETE
============================================================

In [9]:

from pathlib import Path

base_path = Path.cwd()

print("Current working directory:")
print(base_path)

print("\nSearching for World Bank CSV files...\n")

for file in base_path.rglob("*.csv"):
    if "b23ed973" in file.name.lower() or "metadata" in file.name.lower():
        print(file)

Current working directory:
c:\Users\Intel\OneDrive\Desktop\data_eda\notebooks

Searching for World Bank CSV files...

In [10]:
from pathlib import Path

project_root = Path.cwd().parent

print("Project root:")
print(project_root)

print("\nFolders inside project root:")
for item in project_root.iterdir():
    print(item)

Project root:
c:\Users\Intel\OneDrive\Desktop\data_eda

Folders inside project root:
c:\Users\Intel\OneDrive\Desktop\data_eda\.venv
c:\Users\Intel\OneDrive\Desktop\data_eda\metadata
c:\Users\Intel\OneDrive\Desktop\data_eda\notebooks
c:\Users\Intel\OneDrive\Desktop\data_eda\processed
c:\Users\Intel\OneDrive\Desktop\data_eda\raw
c:\Users\Intel\OneDrive\Desktop\data_eda\scripts
c:\Users\Intel\OneDrive\Desktop\data_eda\synthetic

In [11]:

for file in project_root.rglob("*.csv"):
    if "b23ed973" in file.name.lower():
        print(file)

c:\Users\Intel\OneDrive\Desktop\data_eda\raw\kaggle\b23ed973-2503-460a-bdd9-8c998125c5f1_Data.csv
c:\Users\Intel\OneDrive\Desktop\data_eda\raw\kaggle\b23ed973-2503-460a-bdd9-8c998125c5f1_Series - Metadata.csv

In [13]:
# ============================================================
# LOAD WORLD BANK DATA ONLY
# ============================================================

world_bank_df = pd.read_csv(world_bank_data_path)

print("=" * 70)
print("WORLD BANK DATA LOADED SUCCESSFULLY")
print("=" * 70)

print("\nDataset shape:")
print(world_bank_df.shape)

print("\nNumber of rows:", len(world_bank_df))
print("Number of columns:", len(world_bank_df.columns))

print("\n========== COLUMN NAMES ==========")

for i, column in enumerate(world_bank_df.columns, 1):
    print(f"{i}. {column}")

print("\n========== FIRST 5 ROWS ==========")
display(world_bank_df.head())

======================================================================
WORLD BANK DATA LOADED SUCCESSFULLY
======================================================================

Dataset shape:
(16795, 14)

Number of rows: 16795
Number of columns: 14

========== COLUMN NAMES ==========
1. Country Name
2. Country Code
3. Series Name
4. Series Code
5. 2011 [YR2011]
6. 2012 [YR2012]
7. 2013 [YR2013]
8. 2014 [YR2014]
9. 2015 [YR2015]
10. 2016 [YR2016]
11. 2017 [YR2017]
12. 2018 [YR2018]
13. 2019 [YR2019]
14. 2020 [YR2020]

========== FIRST 5 ROWS ==========

,Country Name,Country Code,Series Name,Series Code,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Afghanistan,AFG,Age of the establishment (years),IC.FRM.FCHAR.CAR1,..,..,..,9.5,..,..,..,..,..,..
1,Afghanistan,AFG,Annual employment growth (%),IC.FRM.EMP.GROW.PEFT2,..,..,..,6.9,..,..,..,..,..,..
2,Afghanistan,AFG,Bribery depth (% of public transactions where ...,IC.FRM.BRIB.GRAFT2,..,..,..,34.6,..,..,..,..,..,..
3,Afghanistan,AFG,Bribery incidence (percent of firms experienci...,IC.FRM.BRIB.GRAFT3,..,..,..,46.8,..,..,..,..,..,..
4,Afghanistan,AFG,Capacity utilization (%),IC.FRM.INNOV.T3,..,..,..,80.7,..,..,..,..,..,..

In [14]:
# ============================================================
# WORLD BANK DATA QUALITY INSPECTION
# ============================================================

print("=" * 70)
print("WORLD BANK DATA QUALITY INSPECTION")
print("=" * 70)

# ------------------------------------------------------------
# 1. DUPLICATE ROWS
# ------------------------------------------------------------

duplicate_rows = world_bank_df.duplicated().sum()

print("\n========== DUPLICATE CHECK ==========")
print("Duplicate rows:", duplicate_rows)

# ------------------------------------------------------------
# 2. MISSING VALUES
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing_count = world_bank_df.isna().sum()

missing_percentage = (
    world_bank_df.isna().mean() * 100
).round(2)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": missing_percentage
})

display(
    missing_summary.sort_values(
        "missing_count",
        ascending=False
    )
)

# ------------------------------------------------------------
# 3. CHECK '..' VALUES
# ------------------------------------------------------------

print("\n========== '..' VALUES ==========")

dot_counts = (world_bank_df == "..").sum()

display(
    dot_counts[dot_counts > 0]
    .sort_values(ascending=False)
)

# ------------------------------------------------------------
# 4. UNIQUE COUNTRIES
# ------------------------------------------------------------

print("\n========== COUNTRY CHECK ==========")

print(
    "Unique countries:",
    world_bank_df["Country Code"].nunique()
)

print(
    "Unique country names:",
    world_bank_df["Country Name"].nunique()
)

# ------------------------------------------------------------
# 5. UNIQUE INDICATORS
# ------------------------------------------------------------

print("\n========== INDICATOR CHECK ==========")

print(
    "Unique indicators:",
    world_bank_df["Series Code"].nunique()
)

print(
    "Unique indicator names:",
    world_bank_df["Series Name"].nunique()
)

print("\n========== INSPECTION COMPLETE ==========")

======================================================================
WORLD BANK DATA QUALITY INSPECTION
======================================================================

========== DUPLICATE CHECK ==========
Duplicate rows: 2

========== MISSING VALUES ==========

               missing_count  missing_percentage
Country Code               5                0.03
Series Name                5                0.03
2011 [YR2011]              5                0.03
Series Code                5                0.03
2012 [YR2012]              5                0.03
2013 [YR2013]              5                0.03
2017 [YR2017]              5                0.03
2014 [YR2014]              5                0.03
2015 [YR2015]              5                0.03
2016 [YR2016]              5                0.03
2019 [YR2019]              5                0.03
2018 [YR2018]              5                0.03
2020 [YR2020]              5                0.03
Country Name               3                0.02

========== '..' VALUES ==========

2012 [YR2012]    16454
2020 [YR2020]    16229
2011 [YR2011]    16126
2018 [YR2018]    15880
2015 [YR2015]    15764
2017 [YR2017]    15529
2014 [YR2014]    15434
2016 [YR2016]    14741
2019 [YR2019]    12470
2013 [YR2013]    11206
dtype: int64

========== COUNTRY CHECK ==========
Unique countries: 146
Unique country names: 148

========== INDICATOR CHECK ==========
Unique indicators: 115
Unique indicator names: 115

========== INSPECTION COMPLETE ==========

In [15]:

print("=" * 70)
print("WORLD BANK DATA CLEANING - DUPLICATE REMOVAL")
print("=" * 70)

# Create a working copy
world_bank_clean_df = world_bank_df.copy()

# Check duplicates before removal
duplicates_before = world_bank_clean_df.duplicated().sum()

print("\nDuplicate rows before cleaning:", duplicates_before)

# Remove exact duplicate rows
world_bank_clean_df = world_bank_clean_df.drop_duplicates().reset_index(drop=True)

# Check duplicates after removal
duplicates_after = world_bank_clean_df.duplicated().sum()

print("Duplicate rows after cleaning:", duplicates_after)

print("\nOriginal shape:", world_bank_df.shape)
print("Cleaned shape :", world_bank_clean_df.shape)
print("Rows removed  :", world_bank_df.shape[0] - world_bank_clean_df.shape[0])

print("\n" + "=" * 70)
print("DUPLICATE REMOVAL COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK DATA CLEANING - DUPLICATE REMOVAL
======================================================================

Duplicate rows before cleaning: 2
Duplicate rows after cleaning: 0

Original shape: (16795, 14)
Cleaned shape : (16793, 14)
Rows removed  : 2

======================================================================
DUPLICATE REMOVAL COMPLETE
======================================================================

In [16]:

import numpy as np
import pandas as pd

print("=" * 70)
print("WORLD BANK MISSING VALUE ANALYSIS")
print("=" * 70)

# Create a cleaning copy
world_bank_clean = world_bank_df.copy()

# ------------------------------------------------------------
# 1. Check for World Bank missing-value symbols
# ------------------------------------------------------------

missing_symbols = ["..", "...", "NA", "N/A", ""]

print("\n========== MISSING VALUE SYMBOL CHECK ==========")

for symbol in missing_symbols:
    count = (world_bank_clean == symbol).sum().sum()
    if count > 0:
        print(f"{repr(symbol)} values found: {count}")

# ------------------------------------------------------------
# 2. Convert World Bank missing symbols to NaN
# ------------------------------------------------------------

world_bank_clean = world_bank_clean.replace(
    ["..", "...", "NA", "N/A", ""],
    np.nan
)

print("\n✅ World Bank missing-value symbols converted to NaN.")

# ------------------------------------------------------------
# 3. Missing values by column
# ------------------------------------------------------------

missing_count = world_bank_clean.isna().sum()
missing_percentage = (
    world_bank_clean.isna().mean() * 100
).round(2)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": missing_percentage
})

missing_summary = missing_summary.sort_values(
    "missing_count",
    ascending=False
)

print("\n========== MISSING VALUES BY COLUMN ==========")
print(missing_summary)

# ------------------------------------------------------------
# 4. Dataset shape
# ------------------------------------------------------------

print("\n========== DATASET STATUS ==========")
print("Dataset shape:", world_bank_clean.shape)
print("Total missing values:", world_bank_clean.isna().sum().sum())

print("\n" + "=" * 70)
print("MISSING VALUE ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK MISSING VALUE ANALYSIS
======================================================================

========== MISSING VALUE SYMBOL CHECK ==========
'..' values found: 149833

✅ World Bank missing-value symbols converted to NaN.

========== MISSING VALUES BY COLUMN ==========
               missing_count  missing_percentage
2012 [YR2012]          16459               98.00
2020 [YR2020]          16234               96.66
2011 [YR2011]          16131               96.05
2018 [YR2018]          15885               94.58
2015 [YR2015]          15769               93.89
2017 [YR2017]          15534               92.49
2014 [YR2014]          15439               91.93
2016 [YR2016]          14746               87.80
2019 [YR2019]          12475               74.28
2013 [YR2013]          11211               66.75
Country Code               5                0.03
Series Name                5                0.03
Series Code                5                0.03
Country Name               3                0.02

========== DATASET STATUS ==========
Dataset shape: (16795, 14)
Total missing values: 149901

======================================================================
MISSING VALUE ANALYSIS COMPLETE
======================================================================

In [17]:

print("=" * 70)
print("WORLD BANK INDICATOR AVAILABILITY")
print("=" * 70)

# Count non-missing observations for every indicator
indicator_availability = (
    world_bank_clean
    .groupby(["Series Code", "Series Name"], dropna=False)
    .apply(
        lambda x: x.iloc[:, 4:].notna().sum().sum(),
        include_groups=False
    )
    .reset_index(name="available_observations")
)

# Total possible observations per indicator
number_of_years = 10
number_of_countries = world_bank_clean["Country Code"].nunique()

indicator_availability["possible_observations"] = (
    number_of_years * number_of_countries
)

indicator_availability["availability_percentage"] = (
    indicator_availability["available_observations"]
    / indicator_availability["possible_observations"]
    * 100
).round(2)

# Sort from most available to least available
indicator_availability = indicator_availability.sort_values(
    "availability_percentage",
    ascending=False
)

print("\n========== INDICATOR AVAILABILITY ==========")

print(
    indicator_availability.to_string(index=False)
)

print("\n========== SUMMARY ==========")

print(
    "Total indicators:",
    indicator_availability.shape[0]
)

print(
    "Indicators with >= 50% availability:",
    (
        indicator_availability["availability_percentage"] >= 50
    ).sum()
)

print(
    "Indicators with >= 25% availability:",
    (
        indicator_availability["availability_percentage"] >= 25
    ).sum()
)

print(
    "Indicators with >= 10% availability:",
    (
        indicator_availability["availability_percentage"] >= 10
    ).sum()
)

print("\n" + "=" * 70)
print("INDICATOR AVAILABILITY ANALYSIS COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK INDICATOR AVAILABILITY
======================================================================

========== INDICATOR AVAILABILITY ==========
           Series Code                                                                                        Series Name  available_observations  possible_observations  availability_percentage
    IC.FRM.BRIB.GRAFT2            Bribery depth (% of public transactions where a gift or informal payment was requested)                     150                   1460                    10.27
    IC.FRM.BRIB.GRAFT3               Bribery incidence (percent of firms experiencing at least one bribe payment request)                     150                   1460                    10.27
     IC.FRM.CORR.CORR1                             Percent of firms expected to give gifts in meetings with tax officials                     150                   1460                    10.27
    IC.FRM.CORR.CORR11                                      Percent of firms identifying corruption as a major constraint                     150                   1460                    10.27
 IC.FRM.EMP.GROW.PEFT2                                                                       Annual employment growth (%)                     150                   1460                    10.27
     IC.FRM.CORR.CORR2                              Percent of firms expected to give gifts to secure government contract                     150                   1460                    10.27
     IC.FRM.CORR.CORR3                       Value of gift expected to secure a government contract (% of contract value)                     150                   1460                    10.27
     IC.FRM.CORR.CORR8                               Percent of firms expected to give gifts to get a construction permit                     150                   1460                    10.27
     IC.FRM.CRM.CRIME1                                                               Percent of firms paying for security                     150                   1460                    10.27
   IC.FRM.CRM.CRIME2_C                 If the establishment pays for security, average security costs (% of annual sales)                     150                   1460                    10.27
    IC.FRM.CORR.CRIME9                               Percent of firms identifying the courts system as a major constraint                     150                   1460                    10.27
      IC.FRM.FIN.FIN16                               Percent of firms identifying access to finance as a major constraint                     150                   1460                    10.27
      IC.FRM.FIN.FIN11                                                       Proportion of loans requiring collateral (%)                     150                   1460                    10.27
       IC.FRM.FIN.FIN1                                                   Proportion of investment financed internally (%)                     150                   1460                    10.27
     IC.FRM.FIAS.PEFT4                                                               Percent of firms buying fixed assets                     150                   1460                    10.27
   IC.FRM.FCHAR.LFORM3                                          Percent of firms with legal status of Sole Proprietorship                     150                   1460                    10.27
     IC.FRM.FCHAR.CAR8                                   Percent of firms with at least 10% of government/state ownership                     150                   1460                    10.27
     IC.FRM.FCHAR.CAR7                                            Percent of firms with at least 10% of foreign ownership                     150                   1460                    10.27
     IC.FRM.FCHAR.CAR2                                             Proportion of private domestic ownership in a firm (%)                     150                   1460                    10.27
     IC.FRM.FCHAR.CAR1                                                                   Age of the establishment (years)                     150                   1460                    10.27
      IC.FRM.GEN.GEND2                                      Proportion of permanent full-time workers that are female (%)                     150                   1460                    10.27
     IC.FRM.INFRA.IN11                                  Percent of firms identifying transportation as a major constraint                     150                   1460                    10.27
      IC.FRM.FIN.FIN13                                            Percent of firms using banks to finance working capital                     150                   1460                    10.27
      IC.FRM.FIN.FIN14                                                   Percent of firms with a bank loan/line of credit                     150                   1460                    10.27
      IC.FRM.FIN.FIN20                                                                Percent of firms not needing a loan                     150                   1460                    10.27
       IC.FRM.FIN.FIN2                                                     Proportion of investment financed by banks (%)                     150                   1460                    10.27
       IC.FRM.FIN.FIN7                                                Proportion of working capital financed by banks (%)                     150                   1460                    10.27
      IC.FRM.FIN.FIN22                         Percent of firms using supplier/customer credit to finance working capital                     150                   1460                    10.27
      IC.FRM.FIN.FIN12                                                Percent of firms using banks to finance investments                     150                   1460                    10.27
      IC.FRM.WRKF.WK14                                                                                  Number of workers                     150                   1460                    10.27
       IC.FRM.WRKF.WK1                                                          Percent of firms offering formal training                     150                   1460                    10.27
      IC.FRM.WRKF.WK10              Percent of firms identifying an inadequately educated workforce as a major constraint                     150                   1460                    10.27
        IC.FRM.TRD.TR9                   Percent of firms identifying customs and trade regulations as a major constraint                     150                   1460                    10.27
        IC.FRM.TRD.TR8                                          Proportion of total inputs that are of foreign origin (%)                     150                   1460                    10.27
      IC.FRM.OBS.OBST3                 Percent of firms choosing business licensing and permits as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST7                  Percent of firms choosing customs and trade regulations as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST1                              Percent of firms choosing access to finance as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST12               Percent of firms choosing practices of the informal sector as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST11                          Percent of firms choosing political instability as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST10                              Percent of firms choosing labor regulations as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST13                             Percent of firms choosing tax administration as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST2                                 Percent of firms choosing access to land as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST15                                 Percent of firms choosing transportation as their biggest obstacle                     150                   1460                    10.27
     IC.FRM.OBS.OBST14                                      Percent of firms choosing tax rates as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST4                                     Percent of firms choosing corruption as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST5                                         Percent of firms choosing courts as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.OBS.OBST6                      Percent of firms choosing crime, theft and disorder as their biggest obstacle                     150                   1460                    10.27
       IC.FRM.INNOV.T1                          Percent of firms with an internationally-recognized quality certification                     150                   1460                    10.27
       IC.FRM.INNOV.T5                                                         Percent of firms having their own Web site                     150                   1460                    10.27
       IC.FRM.INNOV.T2                  Percent of firms with an annual financial statement reviewed by external auditors                     150                   1460                    10.27
       IC.FRM.INNOV.T4                                  Percent of firms using technology licensed from foreign companies                     150                   1460                    10.27
       IC.FRM.INNOV.T3                                                                           Capacity utilization (%)                     150                   1460                    10.27
      IC.FRM.WRKF.WK18                                               Proportion of permanent workers (out of all workers)                     150                   1460                    10.27
      IC.FRM.WRKF.WK17                                               Proportion of temporary workers (out of all workers)                     150                   1460                    10.27
      IC.FRM.WRKF.WK19                                  Proportion of skilled workers (out of all production workers) (%)                     150                   1460                    10.27
       IC.FRM.TRD.TR17                          Percent of firms exporting directly or indirectly (at least 10% of sales)                     150                   1460                    10.27
        IC.FRM.TRD.TR5                                           Proportion of total sales that are exported directly (%)                     150                   1460                    10.27
       IC.FRM.REG.BUS5                  Percent of firms identifying business licensing and permits as a major constraint                     150                   1460                    10.27
      IC.FRM.OBS.OBST9                Percent of firms choosing inadequately educated workforce as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.WRKF.WK15                                    Proportion of production workers (out of all permanent workers)                     150                   1460                    10.27
     IC.FRM.REG.REG2_C             If there were visits, average number of visits or required meetings with tax officials                     150                   1460                    10.27
       IC.FRM.REG.REG4                                       Percent of firms identifying tax rates as a major constraint                     150                   1460                    10.27
       IC.FRM.REG.REG6                                    Percent of firms visited or required to meet with tax officials                     150                   1460                    10.27
       IC.FRM.TRD.TR16                                        Percent of firms exporting directly (at least 10% of sales)                     150                   1460                    10.27
       IC.FRM.REG.REG1            Senior management time spent dealing with the requirements of government regulation (%)                     150                   1460                    10.27
      IC.FRM.OBS.OBST8                                    Percent of firms choosing electricity as their biggest obstacle                     150                   1460                    10.27
      IC.FRM.INNOV.T10                                                                 Percent of firms that spend on R&D                     149                   1460                    10.21
       IC.FRM.INNOV.T9                                              Percent of firms that introduced a process innovation                     149                   1460                    10.21
     IC.FRM.CRM.CRIME8                       Percent of firms identifying crime, theft and disorder as a major constraint                     149                   1460                    10.21
     IC.FRM.CRM.CRIME5       Products shipped to supply domestic markets that were lost due to theft (% of product value)                     149                   1460                    10.21
     IC.FRM.CORR.CORR6                            Percent of firms expected to give gifts to get an electrical connection                     149                   1460                    10.21
     IC.FRM.CORR.CORR4                   Percent of firms expected to give gifts to public officials "to get things done"                     149                   1460                    10.21
      IC.FRM.FIN.FIN15                                                Percent of firms with a checking or savings account                     149                   1460                    10.21
   IC.FRM.INFOR.INFOR4                   Percent of firms formally registered when they started operations in the country                     149                   1460                    10.21
    IC.FRM.CRM.CRIME10                                    Percent of firms experiencing losses due to theft and vandalism                     149                   1460                    10.21
       IC.FRM.INNOV.T7                                             Percent of firms that introduced a new product/service                     149                   1460                    10.21
      IC.FRM.INFRA.IN2                                                    Number of electrical outages in a typical month                     149                   1460                    10.21
      IC.FRM.INFRA.IN9                                                     Percent of firms owning or sharing a generator                     149                   1460                    10.21
   IC.FRM.INFOR.INFOR2 Percent of firms identifying practices of competitors in the informal sector as a major constraint                     149                   1460                    10.21
      IC.FRM.GEN.GEND4                                                         Percent of firms with a female top manager                     149                   1460                    10.21
      IC.FRM.GEN.GEND1                                            Percent of firms with female participation in ownership                     149                   1460                    10.21
      IC.FRM.GEN.GEND6                                                    Percent of firms with majority female ownership                     149                   1460                    10.21
   IC.FRM.INFOR.INFOR5                                          Number of years firm operated without formal registration                     149                   1460                    10.21
   IC.FRM.INFOR.INFOR1                                  Percent of firms competing against unregistered or informal firms                     149                   1460                    10.21
       IC.FRM.WRKF.WK9                               Percent of firms identifying labor regulations as a major constraint                     149                   1460                    10.21
        IC.FRM.TRD.TR2                                                                 Days to clear imports from customs                     149                   1460                    10.21
 IC.FRM.SLS.GROW.PEFT1                                                                       Real annual sales growth (%)                     149                   1460                    10.21
       IC.FRM.TRD.TR11                           Percent of firms using material inputs and/or supplies of foreign origin                     149                   1460                    10.21
       IC.FRM.REG.BUS3                                                       Days to obtain a construction-related permit                     149                   1460                    10.21
IC.FRM.PROD.GROW.PEFT3                                                          Real annual labor productivity growth (%)                     149                   1460                    10.21
       IC.FRM.REG.REG5                              Percent of firms identifying tax administration as a major constraint                     149                   1460                    10.21
    IC.FRM.INFRA.IN4_C                If there were outages, average losses due to electrical outages (% of annual sales)                     149                   1460                    10.21
     IC.FRM.INFRA.IN16                                                   Percent of firms experiencing electrical outages                     149                   1460                    10.21
     IC.FRM.INFRA.IN12                                     Percent of firms identifying electricity as a major constraint                     149                   1460                    10.21
    IC.FRM.INFRA.IN3_C                     If there were outages, average duration of a typical electrical outage (hours)                     149                   1460                    10.21
     IC.FRM.INFRA.IN14        Proportion of products lost to breakage or spoilage during shipping to domestic markets (%)                     149                   1460                    10.21
       IC.FRM.INNOV.T8                          Percent of firms whose new product/service is also new to the main market                     149                   1460                    10.21
   IC.FRM.INFRA.IN10_C                     If a generator is used, average proportion of electricity from a generator (%)                     148                   1460                    10.14
      IC.FRM.INFRA.IN6                                                 Number of water insufficiencies in a typical month                     148                   1460                    10.14
     IC.FRM.INFRA.IN17                                                Percent of firms experiencing water insufficiencies                     148                   1460                    10.14

In [18]:

print("=" * 70)
print("WORLD BANK SME-RELEVANT INDICATOR SELECTION")
print("=" * 70)

# Keywords related to SME financial health and business environment
relevant_keywords = [
    "finance",
    "investment",
    "loan",
    "collateral",
    "sales",
    "employment",
    "growth",
    "profit",
    "constraint",
    "corruption",
    "tax",
    "electricity",
    "informal",
    "ownership",
    "fixed assets",
    "working capital",
    "bank",
    "credit",
    "security"
]

# Combine indicator name and code for searching
indicator_text = (
    indicator_availability["Series Name"]
    .fillna("")
    .str.lower()
)

# Find potentially relevant indicators
relevant_mask = indicator_text.apply(
    lambda x: any(keyword in x for keyword in relevant_keywords)
)

world_bank_relevant_indicators = indicator_availability[
    relevant_mask
].copy()

print("\n========== RELEVANT INDICATORS ==========")

print(
    world_bank_relevant_indicators[
        [
            "Series Code",
            "Series Name",
            "available_observations",
            "availability_percentage"
        ]
    ].to_string(index=False)
)

print("\n========== SUMMARY ==========")

print(
    "Total indicators in World Bank dataset:",
    len(indicator_availability)
)

print(
    "Potentially relevant indicators:",
    len(world_bank_relevant_indicators)
)

print("\n" + "=" * 70)
print("INDICATOR SELECTION COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK SME-RELEVANT INDICATOR SELECTION
======================================================================

========== RELEVANT INDICATORS ==========
           Series Code                                                                                        Series Name  available_observations  availability_percentage
    IC.FRM.BRIB.GRAFT2            Bribery depth (% of public transactions where a gift or informal payment was requested)                     150                    10.27
     IC.FRM.CORR.CORR1                             Percent of firms expected to give gifts in meetings with tax officials                     150                    10.27
    IC.FRM.CORR.CORR11                                      Percent of firms identifying corruption as a major constraint                     150                    10.27
 IC.FRM.EMP.GROW.PEFT2                                                                       Annual employment growth (%)                     150                    10.27
     IC.FRM.CRM.CRIME1                                                               Percent of firms paying for security                     150                    10.27
   IC.FRM.CRM.CRIME2_C                 If the establishment pays for security, average security costs (% of annual sales)                     150                    10.27
    IC.FRM.CORR.CRIME9                               Percent of firms identifying the courts system as a major constraint                     150                    10.27
      IC.FRM.FIN.FIN16                               Percent of firms identifying access to finance as a major constraint                     150                    10.27
      IC.FRM.FIN.FIN11                                                       Proportion of loans requiring collateral (%)                     150                    10.27
       IC.FRM.FIN.FIN1                                                   Proportion of investment financed internally (%)                     150                    10.27
     IC.FRM.FIAS.PEFT4                                                               Percent of firms buying fixed assets                     150                    10.27
     IC.FRM.FCHAR.CAR8                                   Percent of firms with at least 10% of government/state ownership                     150                    10.27
     IC.FRM.FCHAR.CAR7                                            Percent of firms with at least 10% of foreign ownership                     150                    10.27
     IC.FRM.FCHAR.CAR2                                             Proportion of private domestic ownership in a firm (%)                     150                    10.27
     IC.FRM.INFRA.IN11                                  Percent of firms identifying transportation as a major constraint                     150                    10.27
      IC.FRM.FIN.FIN13                                            Percent of firms using banks to finance working capital                     150                    10.27
      IC.FRM.FIN.FIN14                                                   Percent of firms with a bank loan/line of credit                     150                    10.27
      IC.FRM.FIN.FIN20                                                                Percent of firms not needing a loan                     150                    10.27
       IC.FRM.FIN.FIN2                                                     Proportion of investment financed by banks (%)                     150                    10.27
       IC.FRM.FIN.FIN7                                                Proportion of working capital financed by banks (%)                     150                    10.27
      IC.FRM.FIN.FIN22                         Percent of firms using supplier/customer credit to finance working capital                     150                    10.27
      IC.FRM.FIN.FIN12                                                Percent of firms using banks to finance investments                     150                    10.27
      IC.FRM.WRKF.WK10              Percent of firms identifying an inadequately educated workforce as a major constraint                     150                    10.27
        IC.FRM.TRD.TR9                   Percent of firms identifying customs and trade regulations as a major constraint                     150                    10.27
      IC.FRM.OBS.OBST1                              Percent of firms choosing access to finance as their biggest obstacle                     150                    10.27
     IC.FRM.OBS.OBST12               Percent of firms choosing practices of the informal sector as their biggest obstacle                     150                    10.27
     IC.FRM.OBS.OBST13                             Percent of firms choosing tax administration as their biggest obstacle                     150                    10.27
     IC.FRM.OBS.OBST14                                      Percent of firms choosing tax rates as their biggest obstacle                     150                    10.27
      IC.FRM.OBS.OBST4                                     Percent of firms choosing corruption as their biggest obstacle                     150                    10.27
       IC.FRM.TRD.TR17                          Percent of firms exporting directly or indirectly (at least 10% of sales)                     150                    10.27
        IC.FRM.TRD.TR5                                           Proportion of total sales that are exported directly (%)                     150                    10.27
       IC.FRM.REG.BUS5                  Percent of firms identifying business licensing and permits as a major constraint                     150                    10.27
     IC.FRM.REG.REG2_C             If there were visits, average number of visits or required meetings with tax officials                     150                    10.27
       IC.FRM.REG.REG4                                       Percent of firms identifying tax rates as a major constraint                     150                    10.27
       IC.FRM.REG.REG6                                    Percent of firms visited or required to meet with tax officials                     150                    10.27
       IC.FRM.TRD.TR16                                        Percent of firms exporting directly (at least 10% of sales)                     150                    10.27
      IC.FRM.OBS.OBST8                                    Percent of firms choosing electricity as their biggest obstacle                     150                    10.27
     IC.FRM.CRM.CRIME8                       Percent of firms identifying crime, theft and disorder as a major constraint                     149                    10.21
   IC.FRM.INFOR.INFOR2 Percent of firms identifying practices of competitors in the informal sector as a major constraint                     149                    10.21
      IC.FRM.GEN.GEND1                                            Percent of firms with female participation in ownership                     149                    10.21
      IC.FRM.GEN.GEND6                                                    Percent of firms with majority female ownership                     149                    10.21
   IC.FRM.INFOR.INFOR1                                  Percent of firms competing against unregistered or informal firms                     149                    10.21
       IC.FRM.WRKF.WK9                               Percent of firms identifying labor regulations as a major constraint                     149                    10.21
 IC.FRM.SLS.GROW.PEFT1                                                                       Real annual sales growth (%)                     149                    10.21
IC.FRM.PROD.GROW.PEFT3                                                          Real annual labor productivity growth (%)                     149                    10.21
       IC.FRM.REG.REG5                              Percent of firms identifying tax administration as a major constraint                     149                    10.21
    IC.FRM.INFRA.IN4_C                If there were outages, average losses due to electrical outages (% of annual sales)                     149                    10.21
     IC.FRM.INFRA.IN12                                     Percent of firms identifying electricity as a major constraint                     149                    10.21
   IC.FRM.INFRA.IN10_C                     If a generator is used, average proportion of electricity from a generator (%)                     148                    10.14
      IC.FRM.FIN.FIN10                                       Value of collateral needed for a loan (% of the loan amount)                     147                    10.07
      IC.FRM.FIN.FIN21                                        Percent of firms whose recent loan application was rejected                     147                    10.07
   IC.FRM.CRM.CRIME3_C                If there were losses, average losses due to theft and vandalism (% of annual sales)                     144                     9.86

========== SUMMARY ==========
Total indicators in World Bank dataset: 116
Potentially relevant indicators: 52

======================================================================
INDICATOR SELECTION COMPLETE
======================================================================

In [19]:

print("=" * 70)
print("CREATING WORLD BANK SELECTED INDICATOR DATASET")
print("=" * 70)

# Get the Series Codes selected in the previous step
selected_series_codes = (
    world_bank_relevant_indicators["Series Code"]
    .dropna()
    .unique()
    .tolist()
)

print("\nNumber of selected indicators:", len(selected_series_codes))

# Filter the cleaned World Bank dataset
world_bank_selected = world_bank_clean[
    world_bank_clean["Series Code"].isin(selected_series_codes)
].copy()

print("\n========== SELECTED DATASET ==========")

print("Shape:", world_bank_selected.shape)

print(
    "Number of countries:",
    world_bank_selected["Country Code"].nunique()
)

print(
    "Number of indicators:",
    world_bank_selected["Series Code"].nunique()
)

print(
    "Number of country names:",
    world_bank_selected["Country Name"].nunique()
)

# ------------------------------------------------------------
# Check observations by indicator
# ------------------------------------------------------------

selected_indicator_summary = (
    world_bank_selected
    .groupby(["Series Code", "Series Name"], dropna=False)
    .apply(
        lambda x: x.iloc[:, 4:].notna().sum().sum(),
        include_groups=False
    )
    .reset_index(name="available_observations")
)

selected_indicator_summary = (
    selected_indicator_summary
    .sort_values(
        "available_observations",
        ascending=False
    )
)

print("\n========== SELECTED INDICATOR COVERAGE ==========")

print(
    selected_indicator_summary.to_string(index=False)
)

print("\n" + "=" * 70)
print("SELECTED WORLD BANK DATASET CREATED")
print("=" * 70)

======================================================================
CREATING WORLD BANK SELECTED INDICATOR DATASET
======================================================================

Number of selected indicators: 52

========== SELECTED DATASET ==========
Shape: (7592, 14)
Number of countries: 146
Number of indicators: 52
Number of country names: 146

========== SELECTED INDICATOR COVERAGE ==========
           Series Code                                                                                        Series Name  available_observations
    IC.FRM.BRIB.GRAFT2            Bribery depth (% of public transactions where a gift or informal payment was requested)                     150
     IC.FRM.CORR.CORR1                             Percent of firms expected to give gifts in meetings with tax officials                     150
    IC.FRM.CORR.CORR11                                      Percent of firms identifying corruption as a major constraint                     150
    IC.FRM.CORR.CRIME9                               Percent of firms identifying the courts system as a major constraint                     150
     IC.FRM.CRM.CRIME1                                                               Percent of firms paying for security                     150
   IC.FRM.CRM.CRIME2_C                 If the establishment pays for security, average security costs (% of annual sales)                     150
     IC.FRM.FCHAR.CAR2                                             Proportion of private domestic ownership in a firm (%)                     150
 IC.FRM.EMP.GROW.PEFT2                                                                       Annual employment growth (%)                     150
     IC.FRM.FCHAR.CAR7                                            Percent of firms with at least 10% of foreign ownership                     150
     IC.FRM.FCHAR.CAR8                                   Percent of firms with at least 10% of government/state ownership                     150
       IC.FRM.FIN.FIN1                                                   Proportion of investment financed internally (%)                     150
     IC.FRM.FIAS.PEFT4                                                               Percent of firms buying fixed assets                     150
      IC.FRM.FIN.FIN14                                                   Percent of firms with a bank loan/line of credit                     150
      IC.FRM.FIN.FIN13                                            Percent of firms using banks to finance working capital                     150
      IC.FRM.FIN.FIN11                                                       Proportion of loans requiring collateral (%)                     150
      IC.FRM.FIN.FIN12                                                Percent of firms using banks to finance investments                     150
      IC.FRM.FIN.FIN16                               Percent of firms identifying access to finance as a major constraint                     150
      IC.FRM.FIN.FIN22                         Percent of firms using supplier/customer credit to finance working capital                     150
      IC.FRM.FIN.FIN20                                                                Percent of firms not needing a loan                     150
       IC.FRM.FIN.FIN2                                                     Proportion of investment financed by banks (%)                     150
      IC.FRM.WRKF.WK10              Percent of firms identifying an inadequately educated workforce as a major constraint                     150
        IC.FRM.TRD.TR9                   Percent of firms identifying customs and trade regulations as a major constraint                     150
       IC.FRM.TRD.TR17                          Percent of firms exporting directly or indirectly (at least 10% of sales)                     150
       IC.FRM.FIN.FIN7                                                Proportion of working capital financed by banks (%)                     150
      IC.FRM.OBS.OBST1                              Percent of firms choosing access to finance as their biggest obstacle                     150
     IC.FRM.OBS.OBST12               Percent of firms choosing practices of the informal sector as their biggest obstacle                     150
     IC.FRM.OBS.OBST13                             Percent of firms choosing tax administration as their biggest obstacle                     150
     IC.FRM.INFRA.IN11                                  Percent of firms identifying transportation as a major constraint                     150
       IC.FRM.REG.REG6                                    Percent of firms visited or required to meet with tax officials                     150
       IC.FRM.TRD.TR16                                        Percent of firms exporting directly (at least 10% of sales)                     150
     IC.FRM.REG.REG2_C             If there were visits, average number of visits or required meetings with tax officials                     150
       IC.FRM.REG.REG4                                       Percent of firms identifying tax rates as a major constraint                     150
       IC.FRM.REG.BUS5                  Percent of firms identifying business licensing and permits as a major constraint                     150
      IC.FRM.OBS.OBST8                                    Percent of firms choosing electricity as their biggest obstacle                     150
      IC.FRM.OBS.OBST4                                     Percent of firms choosing corruption as their biggest obstacle                     150
     IC.FRM.OBS.OBST14                                      Percent of firms choosing tax rates as their biggest obstacle                     150
        IC.FRM.TRD.TR5                                           Proportion of total sales that are exported directly (%)                     150
       IC.FRM.REG.REG5                              Percent of firms identifying tax administration as a major constraint                     149
     IC.FRM.CRM.CRIME8                       Percent of firms identifying crime, theft and disorder as a major constraint                     149
IC.FRM.PROD.GROW.PEFT3                                                          Real annual labor productivity growth (%)                     149
      IC.FRM.GEN.GEND6                                                    Percent of firms with majority female ownership                     149
      IC.FRM.GEN.GEND1                                            Percent of firms with female participation in ownership                     149
   IC.FRM.INFOR.INFOR1                                  Percent of firms competing against unregistered or informal firms                     149
   IC.FRM.INFOR.INFOR2 Percent of firms identifying practices of competitors in the informal sector as a major constraint                     149
 IC.FRM.SLS.GROW.PEFT1                                                                       Real annual sales growth (%)                     149
       IC.FRM.WRKF.WK9                               Percent of firms identifying labor regulations as a major constraint                     149
     IC.FRM.INFRA.IN12                                     Percent of firms identifying electricity as a major constraint                     149
    IC.FRM.INFRA.IN4_C                If there were outages, average losses due to electrical outages (% of annual sales)                     149
   IC.FRM.INFRA.IN10_C                     If a generator is used, average proportion of electricity from a generator (%)                     148
      IC.FRM.FIN.FIN10                                       Value of collateral needed for a loan (% of the loan amount)                     147
      IC.FRM.FIN.FIN21                                        Percent of firms whose recent loan application was rejected                     147
   IC.FRM.CRM.CRIME3_C                If there were losses, average losses due to theft and vandalism (% of annual sales)                     144

======================================================================
SELECTED WORLD BANK DATASET CREATED
======================================================================

In [20]:

print("=" * 70)
print("RESHAPING WORLD BANK DATA TO COUNTRY-YEAR FORMAT")
print("=" * 70)

# Make a copy
world_bank_long = world_bank_selected.copy()

# Year columns
year_columns = [
    "2011 [YR2011]",
    "2012 [YR2012]",
    "2013 [YR2013]",
    "2014 [YR2014]",
    "2015 [YR2015]",
    "2016 [YR2016]",
    "2017 [YR2017]",
    "2018 [YR2018]",
    "2019 [YR2019]",
    "2020 [YR2020]"
]

# ------------------------------------------------------------
# Convert wide format to long format
# ------------------------------------------------------------

world_bank_long = world_bank_long.melt(
    id_vars=[
        "Country Name",
        "Country Code",
        "Series Name",
        "Series Code"
    ],
    value_vars=year_columns,
    var_name="Year",
    value_name="Value"
)

# ------------------------------------------------------------
# Clean the Year column
# ------------------------------------------------------------

world_bank_long["Year"] = (
    world_bank_long["Year"]
    .str.extract(r"(\d{4})")[0]
    .astype(int)
)

# ------------------------------------------------------------
# Convert values to numeric
# ------------------------------------------------------------

world_bank_long["Value"] = pd.to_numeric(
    world_bank_long["Value"],
    errors="coerce"
)

print("\n========== LONG FORMAT ==========")

print("Shape:", world_bank_long.shape)

print(
    "Countries:",
    world_bank_long["Country Code"].nunique()
)

print(
    "Indicators:",
    world_bank_long["Series Code"].nunique()
)

print(
    "Years:",
    sorted(world_bank_long["Year"].unique())
)

print("\n========== FIRST 10 ROWS ==========")

print(
    world_bank_long.head(10).to_string(index=False)
)

print("\n========== MISSING VALUES ==========")

print(
    world_bank_long.isna().sum()
)

print("\n" + "=" * 70)
print("WORLD BANK RESHAPING COMPLETE")
print("=" * 70)

======================================================================
RESHAPING WORLD BANK DATA TO COUNTRY-YEAR FORMAT
======================================================================

========== LONG FORMAT ==========
Shape: (75920, 6)
Countries: 146
Indicators: 52
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020)]

========== FIRST 10 ROWS ==========
Country Name Country Code                                                                             Series Name           Series Code  Year  Value
 Afghanistan          AFG                                                            Annual employment growth (%) IC.FRM.EMP.GROW.PEFT2  2011    NaN
 Afghanistan          AFG Bribery depth (% of public transactions where a gift or informal payment was requested)    IC.FRM.BRIB.GRAFT2  2011    NaN
 Afghanistan          AFG          If a generator is used, average proportion of electricity from a generator (%)   IC.FRM.INFRA.IN10_C  2011    NaN
 Afghanistan          AFG      If the establishment pays for security, average security costs (% of annual sales)   IC.FRM.CRM.CRIME2_C  2011    NaN
 Afghanistan          AFG     If there were losses, average losses due to theft and vandalism (% of annual sales)   IC.FRM.CRM.CRIME3_C  2011    NaN
 Afghanistan          AFG     If there were outages, average losses due to electrical outages (% of annual sales)    IC.FRM.INFRA.IN4_C  2011    NaN
 Afghanistan          AFG  If there were visits, average number of visits or required meetings with tax officials     IC.FRM.REG.REG2_C  2011    NaN
 Afghanistan          AFG                                                    Percent of firms buying fixed assets     IC.FRM.FIAS.PEFT4  2011    NaN
 Afghanistan          AFG                   Percent of firms choosing access to finance as their biggest obstacle      IC.FRM.OBS.OBST1  2011    NaN
 Afghanistan          AFG                          Percent of firms choosing corruption as their biggest obstacle      IC.FRM.OBS.OBST4  2011    NaN

========== MISSING VALUES ==========
Country Name        0
Country Code        0
Series Name         0
Series Code         0
Year                0
Value           67686
dtype: int64

======================================================================
WORLD BANK RESHAPING COMPLETE
======================================================================

In [21]:

print("=" * 70)
print("WORLD BANK COUNTRY-YEAR COVERAGE")
print("=" * 70)

# ------------------------------------------------------------
# 1. Count available indicator observations by country and year
# ------------------------------------------------------------

country_year_coverage = (
    world_bank_long
    .groupby(
        ["Country Code", "Country Name", "Year"]
    )["Value"]
    .count()
    .reset_index(name="available_indicators")
)

# Maximum possible indicators = 52
country_year_coverage["coverage_percentage"] = (
    country_year_coverage["available_indicators"]
    / 52
    * 100
).round(2)

# ------------------------------------------------------------
# 2. Display coverage summary
# ------------------------------------------------------------

print("\n========== COUNTRY-YEAR COVERAGE SUMMARY ==========")

print(
    country_year_coverage["available_indicators"]
    .describe()
)

print("\nCoverage percentage:")
print(
    country_year_coverage["coverage_percentage"]
    .describe()
)

# ------------------------------------------------------------
# 3. Best country-year observations
# ------------------------------------------------------------

print("\n========== TOP COUNTRY-YEAR OBSERVATIONS ==========")

print(
    country_year_coverage
    .sort_values(
        "available_indicators",
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)

# ------------------------------------------------------------
# 4. Countries with the most available data
# ------------------------------------------------------------

country_coverage = (
    world_bank_long
    .groupby(
        ["Country Code", "Country Name"]
    )["Value"]
    .count()
    .reset_index(name="available_observations")
)

country_coverage["coverage_percentage"] = (
    country_coverage["available_observations"]
    / (52 * 10)
    * 100
).round(2)

print("\n========== COUNTRY COVERAGE ==========")

print(
    country_coverage
    .sort_values(
        "coverage_percentage",
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)

print("\n" + "=" * 70)
print("COUNTRY-YEAR COVERAGE CHECK COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK COUNTRY-YEAR COVERAGE
======================================================================

========== COUNTRY-YEAR COVERAGE SUMMARY ==========
count    1460.000000
mean        5.639726
std        16.139779
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        52.000000
Name: available_indicators, dtype: float64

Coverage percentage:
count    1460.000000
mean       10.845644
std        31.038085
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       100.000000
Name: coverage_percentage, dtype: float64

========== TOP COUNTRY-YEAR OBSERVATIONS ==========
Country Code           Country Name  Year  available_indicators  coverage_percentage
         GEO                Georgia  2019                    52                100.0
         HND               Honduras  2016                    52                100.0
         EGY       Egypt, Arab Rep.  2020                    52                100.0
         TZA               Tanzania  2013                    52                100.0
         LBN                Lebanon  2013                    52                100.0
         BIH Bosnia and Herzegovina  2013                    52                100.0
         KEN                  Kenya  2018                    52                100.0
         GHA                  Ghana  2013                    52                100.0
         ZMB                 Zambia  2019                    52                100.0
         CIV          Cote d'Ivoire  2016                    52                100.0
         UGA                 Uganda  2013                    52                100.0
         KGZ        Kyrgyz Republic  2019                    52                100.0
         BTN                 Bhutan  2015                    52                100.0
         BIH Bosnia and Herzegovina  2019                    52                100.0
         IDN              Indonesia  2015                    52                100.0
         ZWE               Zimbabwe  2016                    52                100.0
         LAO                Lao PDR  2016                    52                100.0
         LBR                Liberia  2017                    52                100.0
         BEL                Belgium  2020                    52                100.0
         BLR                Belarus  2013                    52                100.0

========== COUNTRY COVERAGE ==========
Country Code           Country Name  available_observations  coverage_percentage
         EGY       Egypt, Arab Rep.                     156                30.00
         LAO                Lao PDR                     154                29.62
         BLR                Belarus                     104                20.00
         BGR               Bulgaria                     104                20.00
         BIH Bosnia and Herzegovina                     104                20.00
         HUN                Hungary                     104                20.00
         JOR                 Jordan                     104                20.00
         LBN                Lebanon                     104                20.00
         KGZ        Kyrgyz Republic                     104                20.00
         KAZ             Kazakhstan                     104                20.00
         ETH               Ethiopia                     104                20.00
         MAR                Morocco                     104                20.00
         MDA                Moldova                     104                20.00
         HRV                Croatia                     104                20.00
         CZE         Czech Republic                     104                20.00
         EST                Estonia                     104                20.00
         ARM                Armenia                     104                20.00
         ALB                Albania                     104                20.00
         POL                 Poland                     104                20.00
         SRB                 Serbia                     104                20.00

======================================================================
COUNTRY-YEAR COVERAGE CHECK COMPLETE
======================================================================

In [22]:

print("=" * 70)
print("WORLD BANK COUNTRY-YEAR COVERAGE FILTERING")
print("=" * 70)

# Check the coverage dataframe
print("\nOriginal country-year observations:", len(country_year_coverage))

# Coverage threshold
MIN_INDICATORS = 5

# Keep country-years with at least 5 available indicators
wb_usable_coverage = country_year_coverage[
    country_year_coverage["available_indicators"] >= MIN_INDICATORS
].copy()

print("\n========== COVERAGE FILTER ==========")

print("Minimum indicators required:", MIN_INDICATORS)

print("Usable country-year observations:",
      len(wb_usable_coverage))

print("Percentage retained:",
      round(
          len(wb_usable_coverage) /
          len(country_year_coverage) * 100,
          2
      ), "%")

print("\nAvailable indicators distribution:")

print(
    wb_usable_coverage["available_indicators"]
    .describe()
)

print("\n========== TOP COUNTRY-YEAR OBSERVATIONS ==========")

print(
    wb_usable_coverage[
        [
            "Country Name",
            "Country Code",
            "Year",
            "available_indicators",
            "coverage_percentage"
        ]
    ]
    .sort_values(
        "available_indicators",
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)

print("\n" + "=" * 70)
print("COVERAGE FILTER COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK COUNTRY-YEAR COVERAGE FILTERING
======================================================================

Original country-year observations: 1460

========== COVERAGE FILTER ==========
Minimum indicators required: 5
Usable country-year observations: 159
Percentage retained: 10.89 %

Available indicators distribution:
count    159.000000
mean      51.786164
std        0.749386
min       46.000000
25%       52.000000
50%       52.000000
75%       52.000000
max       52.000000
Name: available_indicators, dtype: float64

========== TOP COUNTRY-YEAR OBSERVATIONS ==========
          Country Name Country Code  Year  available_indicators  coverage_percentage
               Albania          ALB  2013                    52                100.0
               Albania          ALB  2019                    52                100.0
             Argentina          ARG  2017                    52                100.0
               Armenia          ARM  2020                    52                100.0
               Armenia          ARM  2013                    52                100.0
            Azerbaijan          AZE  2013                    52                100.0
               Burundi          BDI  2014                    52                100.0
              Bulgaria          BGR  2019                    52                100.0
               Belgium          BEL  2020                    52                100.0
                 Benin          BEN  2016                    52                100.0
            Bangladesh          BGD  2013                    52                100.0
Bosnia and Herzegovina          BIH  2013                    52                100.0
              Bulgaria          BGR  2013                    52                100.0
               Belarus          BLR  2013                    52                100.0
Bosnia and Herzegovina          BIH  2019                    52                100.0
        Czech Republic          CZE  2013                    52                100.0
      Congo, Dem. Rep.          COD  2013                    52                100.0
               Belarus          BLR  2018                    52                100.0
               Bolivia          BOL  2017                    52                100.0
                Bhutan          BTN  2015                    52                100.0

======================================================================
COVERAGE FILTER COMPLETE
======================================================================

In [ ]:

import pandas as pd

print("=" * 70)
print("DATAFRAMES CURRENTLY AVAILABLE")
print("=" * 70)

dataframes = {
    name: obj
    for name, obj in list(globals().items())
    if isinstance(obj, pd.DataFrame)
}

if not dataframes:
    print("❌ No DataFrames are currently loaded.")
else:
    for name, df in dataframes.items():
        print(f"{name}: {df.shape}")

======================================================================
DATAFRAMES CURRENTLY AVAILABLE
======================================================================
main_df: (28, 2)
world_bank_main: (28, 2)
df_temp: (40, 15)
world_bank_df: (16795, 14)
missing_summary: (14, 2)
world_bank_clean_df: (16793, 14)
world_bank_clean: (16795, 14)
indicator_availability: (116, 5)
world_bank_relevant_indicators: (52, 5)
world_bank_selected: (7592, 14)
selected_indicator_summary: (52, 3)
world_bank_long: (75920, 6)
country_year_coverage: (1460, 5)
country_coverage: (146, 4)
wb_usable_coverage: (159, 5)

In [26]:
# ======================================================================
# CREATE FINAL WORLD BANK FILTERED MODELING DATASET
# ======================================================================

print("=" * 70)
print("CREATING FINAL WORLD BANK MODELING DATASET")
print("=" * 70)

# Create a unique list of usable country-year combinations
usable_keys = wb_usable_coverage[
    ["Country Name", "Country Code", "Year"]
].drop_duplicates()

# Keep only observations belonging to usable country-years
world_bank_model_long = world_bank_long.merge(
    usable_keys,
    on=["Country Name", "Country Code", "Year"],
    how="inner"
)

print("\n========== FINAL FILTERED LONG DATA ==========")

print("Shape:", world_bank_model_long.shape)

print(
    "Country-year observations:",
    world_bank_model_long[
        ["Country Code", "Year"]
    ].drop_duplicates().shape[0]
)

print(
    "Countries:",
    world_bank_model_long["Country Code"].nunique()
)

print(
    "Indicators:",
    world_bank_model_long["Series Code"].nunique()
)

print(
    "Years:",
    sorted(world_bank_model_long["Year"].unique())
)

print("\n========== MISSING VALUES ==========")

print(
    world_bank_model_long.isna()
    .sum()
    .sort_values(ascending=False)
)

print("\n" + "=" * 70)
print("FINAL FILTERED WORLD BANK DATASET CREATED")
print("=" * 70)

======================================================================
CREATING FINAL WORLD BANK MODELING DATASET
======================================================================

========== FINAL FILTERED LONG DATA ==========
Shape: (8268, 6)
Country-year observations: 159
Countries: 113
Indicators: 52
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020)]

========== MISSING VALUES ==========
Value           34
Country Name     0
Country Code     0
Series Name      0
Series Code      0
Year             0
dtype: int64

======================================================================
FINAL FILTERED WORLD BANK DATASET CREATED
======================================================================

In [27]:

print("=" * 70)
print("RESHAPING FINAL WORLD BANK MODELING DATASET")
print("=" * 70)

# Pivot indicators into columns
world_bank_model_wide = world_bank_model_long.pivot_table(
    index=["Country Name", "Country Code", "Year"],
    columns="Series Code",
    values="Value",
    aggfunc="first"
).reset_index()

# Remove the columns-axis name created by pivot_table
world_bank_model_wide.columns.name = None

print("\n========== FINAL WIDE DATASET ==========")

print("Shape:", world_bank_model_wide.shape)

print(
    "Countries:",
    world_bank_model_wide["Country Code"].nunique()
)

print(
    "Country-year observations:",
    world_bank_model_wide[
        ["Country Code", "Year"]
    ].drop_duplicates().shape[0]
)

print(
    "Number of World Bank indicators:",
    len(world_bank_model_wide.columns) - 3
)

print("\n========== FIRST 5 ROWS ==========")

print(
    world_bank_model_wide.head().to_string(index=False)
)

print("\n========== MISSING VALUES ==========")

missing_wb_final = (
    world_bank_model_wide.isna()
    .sum()
    .sort_values(ascending=False)
)

print(missing_wb_final[missing_wb_final > 0])

print("\n========== DUPLICATE COUNTRY-YEARS ==========")

duplicate_country_years = (
    world_bank_model_wide
    .duplicated(
        subset=["Country Code", "Year"]
    )
    .sum()
)

print(
    "Duplicate country-year rows:",
    duplicate_country_years
)

print("\n" + "=" * 70)
print("WORLD BANK WIDE FORMAT COMPLETE")
print("=" * 70)

======================================================================
RESHAPING FINAL WORLD BANK MODELING DATASET
======================================================================

========== FINAL WIDE DATASET ==========
Shape: (159, 55)
Countries: 113
Country-year observations: 159
Number of World Bank indicators: 52

========== FIRST 5 ROWS ==========
Country Name Country Code  Year  IC.FRM.BRIB.GRAFT2  IC.FRM.CORR.CORR1  IC.FRM.CORR.CORR11  IC.FRM.CORR.CRIME9  IC.FRM.CRM.CRIME1  IC.FRM.CRM.CRIME2_C  IC.FRM.CRM.CRIME3_C  IC.FRM.CRM.CRIME8  IC.FRM.EMP.GROW.PEFT2  IC.FRM.FCHAR.CAR2  IC.FRM.FCHAR.CAR7  IC.FRM.FCHAR.CAR8  IC.FRM.FIAS.PEFT4  IC.FRM.FIN.FIN1  IC.FRM.FIN.FIN10  IC.FRM.FIN.FIN11  IC.FRM.FIN.FIN12  IC.FRM.FIN.FIN13  IC.FRM.FIN.FIN14  IC.FRM.FIN.FIN16  IC.FRM.FIN.FIN2  IC.FRM.FIN.FIN20  IC.FRM.FIN.FIN21  IC.FRM.FIN.FIN22  IC.FRM.FIN.FIN7  IC.FRM.GEN.GEND1  IC.FRM.GEN.GEND6  IC.FRM.INFOR.INFOR1  IC.FRM.INFOR.INFOR2  IC.FRM.INFRA.IN10_C  IC.FRM.INFRA.IN11  IC.FRM.INFRA.IN12  IC.FRM.INFRA.IN4_C  IC.FRM.OBS.OBST1  IC.FRM.OBS.OBST12  IC.FRM.OBS.OBST13  IC.FRM.OBS.OBST14  IC.FRM.OBS.OBST4  IC.FRM.OBS.OBST8  IC.FRM.PROD.GROW.PEFT3  IC.FRM.REG.BUS5  IC.FRM.REG.REG2_C  IC.FRM.REG.REG4  IC.FRM.REG.REG5  IC.FRM.REG.REG6  IC.FRM.SLS.GROW.PEFT1  IC.FRM.TRD.TR16  IC.FRM.TRD.TR17  IC.FRM.TRD.TR5  IC.FRM.TRD.TR9  IC.FRM.WRKF.WK10  IC.FRM.WRKF.WK9
 Afghanistan          AFG  2014                34.6               34.0                62.6                40.8               29.5                  6.2                 24.2               57.5                    6.9              100.0                0.0                0.0               28.5             84.5               NaN              70.7               2.0               3.9               5.1              47.6              1.5              45.0               NaN               3.8              1.2               2.2               0.5                 41.5                 33.5                 38.3               42.1               65.8                 9.6              12.1                1.0                0.7                5.0              16.2              10.2                    -1.3             27.6                1.5             45.9             39.1             80.5                    3.0              2.3              5.9             1.3            46.5              52.5             11.0
     Albania          ALB  2013                17.6               18.4                20.1                 1.3               53.9                  4.2                  1.3                5.2                    3.5               93.1                6.2                0.0               22.1             81.7             266.9              87.4              12.4              23.0              29.4               8.4              6.9              71.0               3.8              15.2              8.7              13.1               8.0                 46.3                 23.8                 10.5                5.0               20.3                 5.7              12.7               19.9               11.9               11.3               5.7              14.2                    -6.6              3.2                5.7             14.5             13.4             92.2                   -3.5              8.7             12.0             5.2             3.1               6.0              1.7
     Albania          ALB  2019                30.0               34.6                43.4                40.0               67.4                  2.3                  4.5               19.9                    7.1               94.4                5.3                0.0               44.4             80.2             177.3              89.5              21.5              30.4              37.8              21.2             12.6              70.3               0.0               5.6             10.8              20.7              16.9                 44.7                 37.2                 11.9               10.7               43.0                 1.9               3.1               11.3                3.7               21.1               8.4               8.0                    -2.6             16.9                5.7             48.8             29.0             93.2                    3.1             14.9             16.4            10.1             7.7              24.8              7.7
   Argentina          ARG  2017                 7.1                6.0                50.0                39.5               61.9                  1.4                  1.8               14.0                   -0.7               96.7                2.8                0.0               44.3             61.2             219.4              47.8              40.9              29.6              42.4              23.1             23.0              40.5               4.3              57.6              7.8              57.8               7.9                 72.5                 31.1                  3.5               22.8               47.2                 0.8               5.3                5.3                7.8               35.9               1.7               2.1                    -6.5             25.0                3.3             79.0             59.8             41.1                   -6.6              6.8              8.4             2.3            20.0              39.7             49.0
     Armenia          ARM  2013                 7.0                6.1                15.0                 1.9               44.8                  2.5                  5.3                4.6                    1.8               92.5               10.5                0.0               30.5             63.7             258.0              88.0              22.1              43.0              47.3              26.3             14.7              46.1               3.5              23.0             18.2              24.4              10.5                 16.5                 10.7                  5.0                9.6                8.2                 0.2               8.1                6.1               22.2               24.7               4.8               0.8                    -0.9              4.5                1.7             37.1             28.3             76.0                    0.7              7.3              9.1             4.1            21.5               7.7              2.3

========== MISSING VALUES ==========
IC.FRM.GEN.GEND6          7
IC.FRM.CRM.CRIME3_C       6
IC.FRM.FIN.FIN10          4
IC.FRM.FIN.FIN21          3
IC.FRM.INFRA.IN10_C       2
IC.FRM.PROD.GROW.PEFT3    2
IC.FRM.SLS.GROW.PEFT1     2
IC.FRM.GEN.GEND1          1
IC.FRM.INFRA.IN4_C        1
IC.FRM.INFRA.IN12         1
IC.FRM.CRM.CRIME8         1
IC.FRM.INFOR.INFOR1       1
IC.FRM.INFOR.INFOR2       1
IC.FRM.WRKF.WK9           1
IC.FRM.REG.REG5           1
dtype: int64

========== DUPLICATE COUNTRY-YEARS ==========
Duplicate country-year rows: 0

======================================================================
WORLD BANK WIDE FORMAT COMPLETE
======================================================================

In [28]:
# ======================================================================
# WORLD BANK MISSING VALUE IMPUTATION
# ======================================================================

print("=" * 70)
print("WORLD BANK MISSING VALUE IMPUTATION")
print("=" * 70)

# Create a copy
world_bank_imputed = world_bank_model_wide.copy()

# Identifier columns - DO NOT IMPUTE
identifier_columns = [
    "Country Name",
    "Country Code",
    "Year"
]

# World Bank indicator columns
indicator_columns = [
    col for col in world_bank_imputed.columns
    if col not in identifier_columns
]

print("\nNumber of indicator columns:", len(indicator_columns))

# Missing values BEFORE imputation
missing_before = (
    world_bank_imputed[indicator_columns]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_before = missing_before[missing_before > 0]

print("\n========== MISSING VALUES BEFORE IMPUTATION ==========")

print(missing_before)

print(
    "\nTotal missing values:",
    int(missing_before.sum())
)

# Store original missing locations
missing_mask = world_bank_imputed[indicator_columns].isna()

# Median imputation
for column in indicator_columns:

    median_value = world_bank_imputed[column].median()

    world_bank_imputed[column] = (
        world_bank_imputed[column]
        .fillna(median_value)
    )

# Missing values AFTER imputation
missing_after = (
    world_bank_imputed[indicator_columns]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_after = missing_after[missing_after > 0]

print("\n========== MISSING VALUES AFTER IMPUTATION ==========")

if len(missing_after) == 0:
    print("✅ No missing values remain in World Bank indicators.")
else:
    print(missing_after)

print(
    "\nTotal missing values after imputation:",
    int(
        world_bank_imputed[indicator_columns]
        .isna()
        .sum()
        .sum()
    )
)

print("\n========== FINAL DATASET ==========")

print("Shape:", world_bank_imputed.shape)

print(
    "Countries:",
    world_bank_imputed["Country Code"].nunique()
)

print(
    "Country-year observations:",
    world_bank_imputed[
        ["Country Code", "Year"]
    ].drop_duplicates().shape[0]
)

print(
    "Indicators:",
    len(indicator_columns)
)

print("\n" + "=" * 70)
print("WORLD BANK IMPUTATION COMPLETE")
print("=" * 70)

======================================================================
WORLD BANK MISSING VALUE IMPUTATION
======================================================================

Number of indicator columns: 52

========== MISSING VALUES BEFORE IMPUTATION ==========
IC.FRM.GEN.GEND6          7
IC.FRM.CRM.CRIME3_C       6
IC.FRM.FIN.FIN10          4
IC.FRM.FIN.FIN21          3
IC.FRM.PROD.GROW.PEFT3    2
IC.FRM.INFRA.IN10_C       2
IC.FRM.SLS.GROW.PEFT1     2
IC.FRM.INFRA.IN12         1
IC.FRM.GEN.GEND1          1
IC.FRM.INFRA.IN4_C        1
IC.FRM.WRKF.WK9           1
IC.FRM.REG.REG5           1
IC.FRM.INFOR.INFOR1       1
IC.FRM.INFOR.INFOR2       1
IC.FRM.CRM.CRIME8         1
dtype: int64

Total missing values: 34

========== MISSING VALUES AFTER IMPUTATION ==========
✅ No missing values remain in World Bank indicators.

Total missing values after imputation: 0

========== FINAL DATASET ==========
Shape: (159, 55)
Countries: 113
Country-year observations: 159
Indicators: 52

======================================================================
WORLD BANK IMPUTATION COMPLETE
======================================================================

In [29]:

print("=" * 70)
print("FINAL WORLD BANK DATA QUALITY CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. DATASET SHAPE
# ------------------------------------------------------------

print("\n========== DATASET SHAPE ==========")

print("Shape:", world_bank_imputed.shape)

print("Rows:", len(world_bank_imputed))
print("Columns:", len(world_bank_imputed.columns))


# ------------------------------------------------------------
# 2. IDENTIFIER CHECK
# ------------------------------------------------------------

print("\n========== IDENTIFIER CHECK ==========")

print(
    "Unique countries:",
    world_bank_imputed["Country Code"].nunique()
)

print(
    "Unique country names:",
    world_bank_imputed["Country Name"].nunique()
)

print(
    "Country-year observations:",
    world_bank_imputed[
        ["Country Code", "Year"]
    ].drop_duplicates().shape[0]
)


# ------------------------------------------------------------
# 3. DUPLICATE CHECK
# ------------------------------------------------------------

print("\n========== DUPLICATE CHECK ==========")

duplicate_rows = world_bank_imputed.duplicated().sum()

duplicate_country_year = world_bank_imputed.duplicated(
    subset=["Country Code", "Year"]
).sum()

print("Duplicate rows:", duplicate_rows)

print(
    "Duplicate country-year combinations:",
    duplicate_country_year
)


# ------------------------------------------------------------
# 4. MISSING VALUE CHECK
# ------------------------------------------------------------

print("\n========== MISSING VALUE CHECK ==========")

total_missing = world_bank_imputed.isna().sum().sum()

print("Total missing values:", total_missing)

if total_missing == 0:
    print("✅ No missing values remain.")
else:
    print("❌ Missing values still exist.")

    print(
        world_bank_imputed.isna()
        .sum()
        .sort_values(ascending=False)
        .head(20)
    )


# ------------------------------------------------------------
# 5. DATA TYPE CHECK
# ------------------------------------------------------------

print("\n========== DATA TYPES ==========")

print(
    world_bank_imputed.dtypes.value_counts()
)


# ------------------------------------------------------------
# 6. INDICATOR COUNT
# ------------------------------------------------------------

indicator_columns = [
    col for col in world_bank_imputed.columns
    if col not in [
        "Country Name",
        "Country Code",
        "Year"
    ]
]

print("\n========== INDICATOR CHECK ==========")

print("Number of indicators:", len(indicator_columns))

if len(indicator_columns) == 52:
    print("✅ All 52 selected indicators are present.")
else:
    print("⚠️ Expected 52 indicators.")


# ------------------------------------------------------------
# 7. YEAR RANGE
# ------------------------------------------------------------

print("\n========== YEAR CHECK ==========")

print(
    "Years:",
    sorted(world_bank_imputed["Year"].unique())
)

print(
    "Minimum year:",
    world_bank_imputed["Year"].min()
)

print(
    "Maximum year:",
    world_bank_imputed["Year"].max()
)


# ------------------------------------------------------------
# FINAL STATUS
# ------------------------------------------------------------

print("\n" + "=" * 70)

if (
    world_bank_imputed.shape == (159, 55)
    and duplicate_rows == 0
    and duplicate_country_year == 0
    and total_missing == 0
    and len(indicator_columns) == 52
):
    print("✅ WORLD BANK DATASET PASSED FINAL QUALITY CHECK")
    print("✅ READY FOR MODELING / INTEGRATION")
else:
    print("⚠️ QUALITY CHECK REQUIRES REVIEW")

print("=" * 70)

======================================================================
FINAL WORLD BANK DATA QUALITY CHECK
======================================================================

========== DATASET SHAPE ==========
Shape: (159, 55)
Rows: 159
Columns: 55

========== IDENTIFIER CHECK ==========
Unique countries: 113
Unique country names: 113
Country-year observations: 159

========== DUPLICATE CHECK ==========
Duplicate rows: 0
Duplicate country-year combinations: 0

========== MISSING VALUE CHECK ==========
Total missing values: 0
✅ No missing values remain.

========== DATA TYPES ==========
float64    52
str         2
int64       1
Name: count, dtype: int64

========== INDICATOR CHECK ==========
Number of indicators: 52
✅ All 52 selected indicators are present.

========== YEAR CHECK ==========
Years: [np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020)]
Minimum year: 2011
Maximum year: 2020

======================================================================
✅ WORLD BANK DATASET PASSED FINAL QUALITY CHECK
✅ READY FOR MODELING / INTEGRATION
======================================================================

In [30]:

import os

print("=" * 70)
print("SAVING FINAL WORLD BANK PROCESSED DATASET")
print("=" * 70)

# Create processed directory if it doesn't exist
os.makedirs("../processed/world_bank", exist_ok=True)

# Save final dataset
world_bank_processed_path = (
    "../processed/world_bank/world_bank_modeling_ready.csv"
)

world_bank_imputed.to_csv(
    world_bank_processed_path,
    index=False
)

print("\n========== FILE SAVED ==========")

print("File:")
print(world_bank_processed_path)

print("\nShape:", world_bank_imputed.shape)

print("\n✅ FINAL WORLD BANK DATASET SAVED SUCCESSFULLY.")

print("=" * 70)

======================================================================
SAVING FINAL WORLD BANK PROCESSED DATASET
======================================================================

========== FILE SAVED ==========
File:
../processed/world_bank/world_bank_modeling_ready.csv

Shape: (159, 55)

✅ FINAL WORLD BANK DATASET SAVED SUCCESSFULLY.
======================================================================

In [31]:

import pandas as pd

verification_df = pd.read_csv(
    "../processed/world_bank/world_bank_modeling_ready.csv"
)

print("=" * 70)
print("VERIFYING SAVED WORLD BANK DATASET")
print("=" * 70)

print("\nShape:", verification_df.shape)

print(
    "Missing values:",
    verification_df.isna().sum().sum()
)

print(
    "Duplicate rows:",
    verification_df.duplicated().sum()
)

print(
    "Duplicate country-year combinations:",
    verification_df.duplicated(
        subset=["Country Code", "Year"]
    ).sum()
)

print(
    "Indicators:",
    len(verification_df.columns) - 3
)

if (
    verification_df.shape == (159, 55)
    and verification_df.isna().sum().sum() == 0
    and verification_df.duplicated().sum() == 0
    and verification_df.duplicated(
        subset=["Country Code", "Year"]
    ).sum() == 0
):
    print("\nSAVED WORLD BANK DATASET VERIFIED SUCCESSFULLY.")
else:
    print("\n Verification failed.")

print("=" * 70)

======================================================================
VERIFYING SAVED WORLD BANK DATASET
======================================================================

Shape: (159, 55)
Missing values: 0
Duplicate rows: 0
Duplicate country-year combinations: 0
Indicators: 52

SAVED WORLD BANK DATASET VERIFIED SUCCESSFULLY.
======================================================================